version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(levelname)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

root:
    level: INFO
    handlers: [console]
    propagate: true

loggers:
    uvicorn:
        handlers: [console]
        level: INFO
        propagate: false
    uvicorn.error:
        level: INFO
        propagate: false
    uvicorn.access:
        level: INFO
        propagate: false
